.\" plucker-setup.1
.TH PLUCKER-SETUP 1 "Plucker 1.1 - http://plkr.org/"
.SH NAME
plucker-setup \- set up Plucker for the current user
.SH SYNOPSIS
\fBplucker-setup\fR
.SH DESCRIPTION
.B plucker-setup
installs the default configuration files in the user's home directory and optionally installs the viewer application, the ZLib shared library and a sample document on the Palm handheld device.
.SH "AUTHOR"
Michael Nordstrom <micke@sslug.dk>

Report bugs to http://bugs.plkr.org or <plucker-bugs@rubberchicken.org>

